name: Export All Pipeline Images
on: workflow_dispatch 

jobs:
  export-images:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取所有必备镜像
      run: |
        # 1. package 和 deploy 阶段需要的镜像
        docker pull docker:latest
        
        # 2. code-review 阶段需要的镜像
        docker pull node:24-alpine3.21
        
        # 3. build 和 test 阶段需要的镜像
        docker pull maven:3-jdk-8-alpine
        
        # 将它们一次性打包进同一个 tar 文件中！
        docker save -o all-pipeline-images.tar docker:latest node:24-alpine3.21 maven:3-jdk-8-alpine
        
    - name: 上传为可下载附件
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-images
        path: all-pipeline-images.tar
